server:
  port: 8000
spring:
  datasource:
   url: "jdbc:postgresql://localhost:5432/TaskManager"
   username: "Jatin"
   password: "1234"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hiberante:
        SQL: DEBUG
